---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata: 
  name: drone
  namespace: drone
spec:
  releaseName: drone
  chart: 
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: drone
    version: 2.0.0-rc.13
  values:
    sourceControl:
      provider: "gitea"
      gitea:
        server: "http://gitea-http.gitea"
    server:
      alwaysAuth: true
      adminUser: ramon
      host: drone.ramonruettimann.ml
      kubernetes:
        namespace: "drone-builds"
        pipelineServiceAccount: "drone-builder"
      env:
        DRONE_GIT_USERNAME: 
          valueFrom:
            secretKeyRef:
              name: drone-apitoken
              key: username
        DRONE_GIT_PASSWORD: 
          valueFrom:
            secretKeyRef:
              name: drone-apitoken
              key: token
    persistence:
      enabled: true
      existingClaim: drone
    
