apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone
  namespace: drone
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /mnt/data/cluster/drone
    server: 192.168.254.1
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone
  namespace: drone
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
