apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone
  namespace: drone
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/cluster/drone"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone
  namespace: drone
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
