apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
spec:
  rules:
  - host: git.ramonruettimann.ml
    http:
      paths:
      - backend:
          serviceName: gitea-gitea-http
          serviceNamespcae: gitea
          servicePort: 80
