apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        # TODO: check newest image tag
        image: gitea/gitea:1.8.2
        imagePullPolicy: 
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 3000
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 200
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 500Mi
        volumeMounts:
        - name: gitea-data
          mountPath: /home/git/gitea-repositories
        - name: gitea-db
          mountPath: /var/lib/gitea/data
        - name: gitea-configdir
          mountPath: /data/gitea/conf
      initContainers:
          # TODO: init container for migration
      - name: migrate
        image: gitea/gitea:1.8.1
        volumeMounts:
        - name: gitea-db
          mountPath: /db
        - name: gitea-data
          mountPath: /data
        - name: gitea-migration
          mountPath: /tmp/migration
        - name: gitea-configdir
          mountPath: /conf
        env:
        - name: SCRIPT
          value: &script |-
            if [ -e /db/git.db ]; then exit 0; fi
            cd /tmp/migration/
            ls 
            mkdir -p /data/git
            cp -r gitea-repositories /data/
            cp app.ini /conf/
            touch /db/git.db
            sqlite3 /db/git.db <gitea-db.sql
            chown git /db/git.db
            chgrp git /db/git.db
        command: ["/bin/sh", "-c", *script]
      volumes:
      - name: gitea-data
        hostPath:
          path: /mnt/data/cluster/gitea/data
          type: Directory
      - name: gitea-db
        hostPath:
          path: /mnt/data/cluster/gitea/db
          type: Directory
      - name: gitea-config
        configMap:
          name: gitea-app-ini
      - name: gitea-configdir
        emptyDir: {}
      - hostPath:
          path: /mnt/data/cluster/gitea-migration
          type: Directory
        name: gitea-migration
