---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata: 
  name: gitea
  namespace: gitea
spec:
  releaseName: gitea
  chart: 
    git: https://github.com/tommyknows/gitea-helm-chart.git
    ref: master
    path: "."
  values:
    extraVolumes:
      - name: gitea-migration
        hostPath:
          path: /mnt/data/cluster/gitea-migration
          type: Directory
      - name: postgres-migration
        emptyDir: {}
    extraPostgresMounts:
      - name: postgres-migration
        mountPath: /docker-entrypoint-initdb.d
    extraInitContainers:
      - name: migrate
        image: "postgres:11"
        env:
        - name: SCRIPT
          value: &script |-
            cd /tmp/migration/
            cp app.ini /etc/gitea/app.ini
            cp -r gitea-repo/* /datatmp/git/gitea-repositories/
            # copy the sql file to the init entrypoint for postgres to load
            cp gitea-db.sql /docker-entrypoint-initdb.d/
        command: ["/bin/sh",'-c', *script]
        volumeMounts:
        - name: gitea-data
          mountPath: /datatmp
        - name: gitea-config
          mountPath: /etc/gitea
        - name: gitea-migration
          mountPath: /tmp/migration
        - name: postgres-migration
          mountPath: /docker-entrypoint-initdb.d
    ingress:
      enabled: true
      useSSL: true
      ## annotations used by the ingress - ex for k8s nginx ingress controller:
      ingress_annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
    service:
      http:
        serviceType: ClusterIP
        port: 3000
        externalPort: 443
        externalHost: git.ramonruettimann.ml
      ssh:
        serviceType: NodePort
        port: 22
        nodePort: 30222
        externalPort: 8022
        externalHost: git.ramonruettimann.ml
    
    persistence:
      enabled: true
      existingGiteaClaim: gitea-gitea
      existingPostgresClaim: gitea-postgres

