apiVersion: v1
kind: Secret
metadata:
  name: gitea-db
  labels:
    app: postgres
    chart: RELEASE-NAME-gitea
    release: RELEASE-NAME
    heritage: Tiller
type: Opaque
data:
 
  
  dbPassword: "MEp0WXJRNzRqag=="
