apiVersion: v1
kind: Service
metadata:
  name: gitea-http
  namespace: gitea
  labels:
    app: gitea
    webservice: "true"
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: gitea-http
  selector:
    app: gitea
    webservice: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  namespace: gitea
  labels:
    app: gitea
    webservice: "true"
spec:
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
  selector:
    app: gitea
    webservice: "true"
