apiVersion: v1
kind: Service
metadata:
  name: gitea-http
  namespace: gitea
  labels:
    app: gitea
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: gitea
---
# Source: gitea/templates/gitea/gitea-ssh-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  labels:
    app: gitea
spec:
  type: ClusterIP
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
  selector:
    app: gitea
