apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-gitea-http
  labels:
    app: RELEASE-NAME-gitea
    chart: "gitea-1.6.1"
    release: "RELEASE-NAME"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: RELEASE-NAME-gitea
---
# Source: gitea/templates/gitea/gitea-ssh-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-gitea-ssh
  labels:
    app: RELEASE-NAME-gitea
    chart: "gitea-1.6.1"
    release: "RELEASE-NAME"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
  selector:
    app: RELEASE-NAME-gitea
