apiVersion: v1
kind: Service
metadata:
  name: gitea-http
  namespace: gitea
  labels:
    app: gitea
    chart: "gitea-1.9.3"
    release: "gitea"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: gitea
    webservice: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  namespace: gitea
  labels:
    app: gitea
    chart: "gitea-1.9.3"
    release: "gitea"
    heritage: "Tiller"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.2
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
  selector:
    app: gitea
