apiVersion: v1
kind: Service
metadata:
  name: gitea-http
  namespace: gitea
  labels:
    app: gitea
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: gitea
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  namespace: gitea
  labels:
    app: gitea
spec:
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
  selector:
    app: gitea
