apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-gitea
  namespace: gitea
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/cluster/gitea"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-gitea
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
