apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-provisioner
spec:
  capacity:
    storage: 8Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /mnt/data
    server: 192.168.254.1
    readOnly: false
