---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata: 
  name: gitea
  namespace: gitea
spec:
  releaseName: gitea
  chart: 
    git: https://github.com/jfelten/gitea-helm-chart.git
    ref: master
    path: "."
  values:
    ingress:
      enabled: true
      useSSL: true
      ## annotations used by the ingress - ex for k8s nginx ingress controller:
      ingress_annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
    service:
      http:
        serviceType: ClusterIP
        port: 3000
        externalPort: 443
        externalHost: git.ramonruettimann.ml
      ssh:
        serviceType: NodePort
        port: 22
        nodePort: 30222
        externalPort: 8022
        externalHost: git.ramonruettimann.ml
    
    persistence:
      enabled: true
      giteaSize: 10Gi
      postgresSize: 5Gi
      storageClass: nfs
      accessMode: ReadWriteMany
      annotations:
        "helm.sh/resource-policy": keep

