---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata: 
  name: nfs-provisioner
  namespace: nfs
spec:
  releaseName: nfs-provisioner
  chart:
    name: stable/nfs-server-provisioner
  values: 
    persistence:
      accessMode: ReadWriteMany
      enabled: true
      size: 8Gi
      storageClass: "nfs-provisioner"
    storageClass:
      reclaimPolicy: Retain
