---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata: 
  name: metallb
  namespace: metallb
spec:
  releaseName: metallb
  chart: 
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.9.5
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.1.150-192.168.1.155
